### ISSUE TITLE
Compiler issue with example

### ISSUE THREAD

**Issue by seamusdemora** [tranter/blogs#2]
Hello,

Copied your example from [your blog post](https://www.ics.com/blog/gpio-programming-exploring-libgpiod-library), and stored it in the file `~/blinky_c/blinky-i.c`. Tried compilation as follows: 
```
$ gcc -o blinky -gpiod blinky-i.c
gcc: error: unrecognized debug output level ‘piod’
``` 
No idea where this comes from as I've checked the source file, and found no instance of `piod`. 

My system is RPi 5 running `bookworm` w/Kernel:		 6.1.0-rpi7-rpi-2712

**Comment by tranter** [comment]
The correct compile command line would be something like this:

gcc -o blinky blink-i.c -l gpiod

Or better yet, use the source code here https://github.com/tranter/blogs/tree/master/gpio/part9 and use CMake to build it.

**Comment by seamusdemora** [comment]
Thank you! I was following some answer from SO without checking/verifying it. 

And thanks (again) for the tip about [CMake](https://cmake.org/getting-started/); I'm just reading about it now. AIUI so far, it's a build system for cross-compilation. I don't need that at present as I'm compiling everything directly on my Pi, but it's surely a good thing to know about for larger compile jobs.

**Comment by tranter** [comment]
Resolved.
